import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar'
import getCurrentUser from './actions/getCurrentUser'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar currentUser={currentUser}/>
          {children}
          <Script 
            src="//dapi.kakao.com/v2/maps/sdk.js?appkey=aebd306e8176d000434679d11a0e5cae&libraries=services,clusterer&autoload=false"
          />
      </body>
    </html>
  )
}
